# Generated by Django 6.0.3 on 2026-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao_resumida',
            field=models.TextField(blank=True),
        ),
    ]
