# Generated by Django 6.0.3 on 2026-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
