# Generated by Django 6.0.3 on 2026-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modulo_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='pdf',
        ),
        migrations.AddField(
            model_name='aula',
            name='arquivo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
